// <auto-generated />
namespace HelloEmberRouter.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    
    public sealed partial class EmailTurnsAlias : IMigrationMetadata
    {
        string IMigrationMetadata.Id
        {
            get { return "201207050814472_EmailTurnsAlias"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return "H4sIAAAAAAAEAM1Yy3LbNhTdd6b/wOGqXUSQnSwSD5WMI1mtp5GdMe1kDZFXMiZ4sAToSN+WRT+pv5ALPkCKlGTKcpvsyMt7z30QODjkv9/+Cd6tBPceINVMyZF/Mhj6HshIxUwuR35mFi9e++/e/vpLcBGLlfep8ntp/TBS6pF/b0xyRoiO7kFQPRAsSpVWCzOIlCA0VuR0OHxDTk4IIISPWJ4X3GTSMAH5Dd6OlYwgMRnlMxUD16Udn4Q5qndFBeiERjDy/wTO1YWYQ3qjMgPpoAjxvXPOKJYTAl/4XvLq7E5DaFIll2FCDaP8dp0APl9QrqEs/ix51bf+4amtn1AplUE4JZ/Uv+86w94ucAZmbcvK+xv5OAZDI9N0Qre/YL1hQNPHVCWQmvUNLMrQy9j3yGYcaQe6sEaMzY5X0rw89b2rjHM65+CGhFMMjUrhD5CQUgPxR2pw5NLGQl59J2srx5Sl2tjLKhW+ElxavjdlK4g/gFyae5duRleVBS99704yXIkYZNIMtpS3P/UH+qMy5yvxwLQnp8M9aYv7/VkvBV3CXcqftd8+iT/DXDPzvHPuk/f2K7Or8X/PO0Uemiv15T9OHJCaILq0kXMFw21ZFhUqAZP31gqrNoMUESGYTZ7BJVpnKIhzUFHQ1kpczpqfSUHQFZGTHUwezGiS4JAazF5avLCg9fGL8HBGFQUGifQWYnXVukxIZbhFWk/tOGLIeWpCDZ1T+9rGsei49Zpwlas16DaB13OvAux1EbTjgBtsPR2ao5xidwJpOW8UXEk7zpUyNowop+mWk2GseCbkrtNlX3SD85sgDXN/rJrEm1C1tT9SScpNmNLUH6Om2I3pOGt/JMeZTSBn7I/jOLCJ44wHvDPHaRuvzFm7SAFpLbv2GiedRd7SJ+1Ns49x2i4uu2OeFsME5W5/XFB2tn/h4ns4ogcW51t/rQ2IgXUYhH/zMWfYb+0wo5ItQJtb9QVQGyE7vW7J0SdIRaJ1"
                       + "zH9Svchs948qwwNVU0cqygeaRvc0/U3Q1e9Hy7/j0DYkXQXVFXDHKbadJT5BhR2F1VJWR2G11dIBYIcpoO4x3ksF7RNBBROM/HiusPyizFo8PVEidYkpIM3v4WACmi1rCPt1LCGy35w1aOVzKReqGji21qyocmm9jxkYGuOEzlPDFtgIPo5A61zBfqI8QxcrPuJLeZ2ZJDPnWoOY840vvYDsz5/rwM2ag+vE3unnaAHLZNgCXMv3GeOxq3va3cm7IOxiKbkLq0IFj3DLtUO6UrInUDm+CSQgLfPdgkg4gulrGdIH2F3b4zPcnFgwYXSZUqFLjDre/p4h9v/M2+95lF4+0REAAA=="; }
        }
    }
}
