// <auto-generated />
namespace HelloEmberRouter.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    
    public sealed partial class Init : IMigrationMetadata
    {
        string IMigrationMetadata.Id
        {
            get { return "201207050803434_Init"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return "H4sIAAAAAAAEAM1YyXLbRhC9pyr/gMIpOZhDyT44KtAumRQTVUzJJUjOeQg0qSnPgmAGMvltOeST8gvpwTLYSAoUneUGNLpfL5h584C//vgzeL8R3HuCVDMlJ/7ZaOx7ICMVM7me+JlZvXrrv3/3/XfBVSw23ufK77X1w0ipJ/6jMckFITp6BEH1SLAoVVqtzChSgtBYkfPx+CdydkYAIXzE8rzgLpOGCchv8HaqZASJyShfqBi4Lu34JMxRvRsqQCc0gon/C3CursQS0juVGUhHRYjvXXJGsZwQ+Mr3kjcXDxpCkyq5DhNqGOX32wTw+YpyDWXxF8mbofWPz239hEqpDMIp+aL+fdcZ9naFMzBbW1be38THMRgamaYTuv0K25YBTZ9SlUBqtnewKkOvY98j7TjSDXRhjRibHa+keX3uezcZ53TJwQ0JpxgalcLPICGlBuJP1ODIpY2FvPpe1k6OOUu1sZdVKnwluLR8b842EH8EuTaPLt2CbioLXvreg2S4EjHIpBnsKO9w6o/0v8p8JSjjR6Y9Ox8fSFvcH856LegaHtJjEx/ud0ji32Cpmfm2cx6S9/4rs6vxX887Rx5aKvXlH04ckJog+rSRcwXDbVkWFSoBsw/WCpsugxQRIZg2zyBn1hkK4hxVFLSzEpez5mdSEHRF5GQPkwcLmiQ4pAazlxYvLGh9+io8nlFFgUEivYNYXbUuE1IZbpHOUzuOGHKemlFDl9S+tmksem6DJlzl6gy6S+D13KsAe10E7TngRjtPh+Yo59idQFrOGwVX0p5zpYwNI8ppuuNkmCqeCbnvdDkU3eD8JkjDPByrJvEmVG0djlSSchOmNA3HqCm2NR1nHY7kOLMJ5IzDcRwHNnGc8Yh35jit9cqctY8UkM6y665x0lvkHX3S3TSHGKfr4rI75ukwTFDu9ucFZW/7Fy6+hyN6YnG+9bfagBhZh1H4O59yhv3WDgsq2Qq0uVdfALURstPbjhx9gVQk"
                       + "Wsf8f6oXme3+WWV4pGrqSUX5RNPokaY/CLr58WT5dxpaS9JVUH0Bd5pi21viC1TYSVgdZXUSVlctHQF2nALqH+ODVNAhEVQwwcSPlwrLL8qsxdMLJVKfmALS/B4OZqDZuoawX8cSIvvNWYNWPtdypaqBY2vNiiqXzvtYgKExTugyNWyFjeDjCLTOFexnyrN8sS8hvpa3mUkyc6k1iCVvfekF5HD+XAe2aw5uE3unv0ULWCbDFuBWfsgYj13d8/5O3gdhF0vJXVgVKniEW28d0o2SA4HK8c0gAWmZ7x5EwhFM38qQPsH+2p6fYXtiwYzRdUqFLjHqePt7htj/M+/+BiuuktvREQAA"; }
        }
    }
}
